# Generated by Django 4.1.3 on 2022-12-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_app_env_vars_alter_container_env_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
